server:
  tomcat:
    basedir: /home/cloud/spring-tomcat/${spring.application.name}
  port: 10017
  servlet:
    context-path: /
swagger:
  enabled: true
  title: crscholar服务-开发环境
  description: crscholar服务API
  version: 2.0
  contact:
    name: hezhigang
    email: hezhigang@hnwdkj.com
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
    health-check-url-path: /actuator/health
  client:
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://192.168.1.104:8761/eureka/
management:
  health:
    elasticsearch:
      enabled: false
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      ######################################################################

spring:
  # zipkin:
  #   baseUrl: http://192.168.1.104:10003
  # sleuth:
  #   sampler:
  #     probability: 1
  data:
    elasticsearch:
      cluster-name: wdkj
      cluster-nodes: 192.168.1.11:8300,192.168.1.12:8300,192.168.1.13:8300,192.168.1.14:8300,192.168.1.15:8300


