global:
  baidu:
    username: wdxxkj2014
    password: hr@hnwdkj.com
    token: bcb491d69976e38bb84793606ec7169e
    account-type: 1

spring:
  data:
    elasticsearch:
      cluster-nodes: 192.168.1.75:8300,192.168.1.76:8300,192.168.1.77:8300
      cluster-name: wdkj-test