server:
  tomcat:
    basedir: /home/cloud/spring-tomcat/${spring.application.name}
  port: 10011
  servlet:
    context-path: /
swagger:
  title: 用户和机构-开发环境
  description: 用户和机构API，用于用户维护和机构管理
  version: 2.0
  enabled: true
  contact:
    name: hezhigang
    email: hezhigang@hnwdkj.com
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
    health-check-url-path: /actuator/health
  client:
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://192.168.1.104:8761/eureka/
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
feign:
  hystrix:
    enabled: false
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 180000
######################################################################
ribbon:
  ReadTimeout: 60000  #请求处理的超时时间
  SocketTimeout: 60000
  ConnectTimeout: 60000  #ribbon请求连接的超时时间
  OkToRetryOnAllOperations: false
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2

spring:
  # zipkin:
  #   baseUrl: http://192.168.1.104:10003
  # sleuth:
  #   sampler:
  #     probability: 1
  redis:
    host: 192.168.1.95
    port: 6379
    database: 13
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://192.168.1.36:3306/${spring.application.name}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: dev
    password: dev123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      max-open-prepared-statements: 20
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query: "select 'x'"
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      min-idle: 30
      max-idle: 50
      max-wait-millis: 1000
      initial-size: 1
      max-total: 200
cas:
  server-url-prefix: http://sso.hnlat.cc
  server-login-url: http://sso.hnlat.cc/login
  client-host-url: http://dev.cloud.hnlat.cc/uo-server
  authentication-url-patterns: /login/info
  logout-url-patterns: /*
  validation-url-patterns: /*
  request-wrapper-url-patterns: /*
