server:
  port: 10019
  servlet:
    context-path: /
swagger:
  enabled: true
  title: bse接口-测试环境
  description: bse接口API
  version: 1.0
  contact: 
    name: yangshuaif
    email: yangshuaif@hnwdkj.com
eureka:   
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
    health-check-url-path: /actuator/health
  client:
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5 
    serviceUrl:
      defaultZone: http://192.168.1.105:8761/eureka/
management:
  security: 
    enabled: false  
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 
######################################################################


spring:
  data:
    elasticsearch:
      cluster-nodes: 192.168.1.11:8300,192.168.1.12:8300,192.168.1.13:8300,192.168.1.14:8300,192.168.1.15:8300
      cluster-name: wdkj
      #cluster-nodes: 192.168.1.75:8300,192.168.1.76:8300,192.168.1.77:8300
      # wdkj_test/wdkj
      #cluster-name: wdkj_test
  jpa: 
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate: 
      ddl-auto: update
  datasource:
    school:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://rm-bp16zs74lzakjc7gco.mysql.rds.aliyuncs.com:3306/library?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: user_query
      password: TGEZWx5cfKG9
      default-auto-commit: true
      dbcp2:
        max-open-prepared-statements: 20
        pool-prepared-statements: true
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        validation-query: "select 'x'"
        min-evictable-idle-time-millis: 300000
        time-between-eviction-runs-millis: 60000
        min-idle: 30
        max-idle: 50
        max-wait-millis: 1000
        initial-size: 1
        max-total: 200 
    xk:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.31:3306/xk?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root@123
      default-auto-commit: true
      dbcp2:
        max-open-prepared-statements: 20
        pool-prepared-statements: true
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        validation-query: "select 'x'"
        min-evictable-idle-time-millis: 300000
        time-between-eviction-runs-millis: 60000
        min-idle: 30
        max-idle: 50
        max-wait-millis: 1000
        initial-size: 1
        max-total: 200 